### PR TITLE
Upx compress executable

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by braginini** [comment]
Good job @messense 
Did you notice the size issue in our slack channel?

**Comment by messense** [comment]
I've seen the comment here https://github.com/messense/openwrt-netbird/issues/6#issuecomment-1195506325.

It's still quite large after UPX compression, ~3MB.

**Comment by braginini** [comment]
> I've seen the comment here [#6 (comment)](https://github.com/messense/openwrt-netbird/issues/6#issuecomment-1195506325).
> 
> It's still quite large after UPX compression, ~3MB.

Got it! We had a discussion in our slack channel recently about it as well. 
Thank you very much!

**Comment by messense** [comment]
image

It's relatively small compared to tailscale though. 🤪

**Comment by braginini** [comment]
so the binary size is 3MB after installation? Wow!

**Comment by messense** [comment]
Yes, around 3.6MB. You can download the artifacts here: https://github.com/messense/openwrt-netbird/actions/runs/2745399509

**Comment by braginini** [comment]
Perfect! Thank you, mate. 
I will [play around with it in the following days.

**Comment by mlsmaycon** [comment]
@messense really awesome. 

Compared to the decompressed binaries from your previous build, it went down from 15MB to 3.2MB:
image

**Pull request merged**
